version: '3.8'

services:
  db:
    image: postgres:lateyst
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: symfony_db
    ports:
      - "5432:5432"
