version: '3.8'

services:
  php:
    build:
      context: ./Docker/php
    volumes:
      - .:/var/www/html
    links:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/symfonydb
    ports:
      - "8080:9000"
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./Docker/db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - php